VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://packages.debian.org/bullseye/xz-utils

build:
  FROM $UDCBASE+builder
  # NOTE: The builder already installs this package so we just
  # save the artifact thats already part of the builder image.
  SAVE ARTIFACT /tmp/changed-xz/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/xz" ]
    COPY $UDCBASE/xz+build/ /
  END
