VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian
IMPORT github.com/brad-jones/earthly-devcontainer/debian/sudo
IMPORT github.com/brad-jones/earthly-devcontainer/debian/gosu
IMPORT github.com/brad-jones/earthly-devcontainer/debian/socat
IMPORT github.com/brad-jones/earthly-devcontainer/debian/hooks
IMPORT github.com/brad-jones/earthly-devcontainer/debian/entrypoint

# Create our entrypoint that will execute each time the devcontainer is started.
#
# This is designed to work with: "overrideCommand": false
# If this property in the devcontainer.json config is set to true (the default)
# then the entrypoint will not be executed.
#
# NOTE: The entrypoint will execute with root permissions so it can do things
# like setup permissions to the mounted docker socket & then it will use gosu
# to switch to the unprivilaged user.
#
# see: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-startup-commands-to-the-docker-image-instead

ARG USERNAME="code"
ARG USER_UID="1000"
ARG USER_GID="${USER_UID}"
ARG DOCKER_SOURCE_SOCKET="/var/run/docker-host.sock"
ARG DOCKER_TARGET_SOCKET="/var/run/docker.sock"
ARG ENTRYPOINT_LOGS="/tmp/entrypoint-logs"

build:
  FROM debian+builder
  DO sudo+INSTALL
  COPY ./install-entrypoint.bash /usr/local/bin/install-entrypoint
  RUN chmod +x /usr/local/bin/install-entrypoint
  DO debian+FROM_NOW
  # see: https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user
  RUN groupadd --gid "$USER_GID" "$USERNAME"
  RUN useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME"
  RUN echo "$USERNAME ALL=(root) NOPASSWD:ALL" >"/etc/sudoers.d/$USERNAME"
  RUN chmod 0440 "/etc/sudoers.d/$USERNAME"
  # also: https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
  RUN mkdir /bashhistory
  RUN touch /bashhistory/.bash_history
  RUN chown -R "$USERNAME" /bashhistory
  RUN echo "export PROMPT_COMMAND='history -a' && export HISTFILE=/bashhistory/.bash_history" >>"/home/$USERNAME/.bashrc"
  RUN install-entrypoint
  DO debian+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  DO sudo+INSTALL
  DO gosu+INSTALL
  DO socat+INSTALL
  DO hooks+INSTALL
  IF [ ! -f "/entrypoint.bash" ]
    COPY entrypoint+build/ /
    ENTRYPOINT [ "/entrypoint.bash" ]
    CMD [ "sleep", "infinity" ]
  END
