VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://www.openssh.com

build:
  FROM $UDCBASE+builder
  DO $UDCBASE+FROM_NOW
  RUN apt-get -y install --no-install-recommends openssh-client
  DO $UDCBASE+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/ssh" ]
    COPY $UDCBASE/openssh-client+build/ /
  END
