VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian
IMPORT github.com/brad-jones/earthly-devcontainer/debian/git

# see: https://git-scm.com

build:
  FROM debian+builder
  DO debian+FROM_NOW
  RUN apt-get -y install --no-install-recommends git
  DO debian+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/git" ]
    COPY git+build/ /
  END
