VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://linux.die.net/man/1/envsubst

build:
  FROM $UDCBASE+builder
  DO $UDCBASE+FROM_NOW
  RUN apt-get -y install --no-install-recommends gettext-base
  DO $UDCBASE+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/envsubst" ]
    COPY $UDCBASE/envsubst+build/ /
  END
