VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

INSTALL:
  COMMAND
  DO $UDCBASE/ca-certificates+INSTALL
  DO $UDCBASE/curl+INSTALL
  DO $UDCBASE/envsubst+INSTALL
  DO $UDCBASE/git+INSTALL
  DO $UDCBASE/gpg+INSTALL
  DO $UDCBASE/openssh-client+INSTALL
  DO $UDCBASE/procps+INSTALL
  DO $UDCBASE/socat+INSTALL
  DO $UDCBASE/sudo+INSTALL
  DO $UDCBASE/unzip+INSTALL
  DO $UDCBASE/xz+INSTALL
  DO $UDCBASE/zip+INSTALL
