VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://man7.org/linux/man-pages/man1/procps.1.html

build:
  FROM $UDCBASE+builder
  DO $UDCBASE+FROM_NOW
  RUN apt-get -y install --no-install-recommends procps
  DO $UDCBASE+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/procps" ]
    COPY $UDCBASE/procps+build/ /
  END
