VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian
IMPORT github.com/brad-jones/earthly-devcontainer/debian/curl

build:
  FROM debian+builder
  # NOTE: The builder already installs this package so we just
  # save the artifact thats already part of the builder image.
  SAVE ARTIFACT /tmp/changed-curl/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/curl" ]
    COPY curl+build/ /
  END
