VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

build:
  FROM $UDCBASE+builder
  # NOTE: The builder already installs this package so we just
  # save the artifact thats already part of the builder image.
  SAVE ARTIFACT /tmp/changed-ca-certificates/*

INSTALL:
  COMMAND
  IF [ ! -f "/etc/ca-certificates.conf" ]
    COPY $UDCBASE/ca-certificates+build/ /
  END
