VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://linux.die.net/man/1/unzip

build:
  FROM $UDCBASE+builder
  # NOTE: The builder already installs this package so we just
  # save the artifact thats already part of the builder image.
  SAVE ARTIFACT /tmp/changed-unzip/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/unzip" ]
    COPY $UDCBASE/unzip+build/ /
  END
