VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian:master
FROM debian+base
DO debian/ca-certificates+INSTALL
#DO ../utils+INSTALL_HOOKS
#DO ../utils+INSTALL_ENTRYPOINT
#SAVE IMAGE ghcr.io/brad-jones/earthly-devcontainer/devcontainer:latest

# https://github.com/brad-jones/hashdir/blob/master/.devcontainer/Dockerfile
