VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://www.sudo.ws

build:
  FROM $UDCBASE+builder
  DO $UDCBASE+FROM_NOW
  RUN apt-get -y install --no-install-recommends sudo
  DO $UDCBASE+TO_NOW
  RUN rm -rf /tmp/changed-default/lib
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/sudo" ]
    COPY $UDCBASE/sudo+build/ /
  END
