VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian
IMPORT github.com/brad-jones/earthly-devcontainer/debian/node

ARG NODE_VERSION="16.13.2"
ARG NODE_SHA256="a0f23911d5d9c371e95ad19e4e538d19bffc0965700f187840eb39a91b0c3fb0"
ARG NPM_VERSION="8.3.2"

# see: https://nodejs.org

build:
  FROM debian+builder
  RUN curl -L "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" -o /tmp/nodejs.tar.gz
  RUN echo "${NODE_SHA256} /tmp/nodejs.tar.gz" | sha256sum --check --status
  DO debian+FROM_NOW
  RUN tar -C /usr/local -xzf /tmp/nodejs.tar.gz
  RUN mv /usr/local/node-v${NODE_VERSION}-linux-x64 /usr/local/nodejs
  RUN ln -s /usr/local/nodejs/bin/node /usr/bin/node
  RUN ln -s /usr/local/nodejs/bin/npm /usr/bin/npm
  RUN ln -s /usr/local/nodejs/bin/npx /usr/bin/npx
  RUN npm install -g npm@${NPM_VERSION}
  DO debian+TO_NOW
  RUN rm -rf /tmp/changed-default/root
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/node" ]
    COPY node+build/ /
  END
