VERSION --use-cache-command 0.6

debian:
  ARG VERSION="11"
  FROM github.com/brad-jones/earthly-devcontainer/base+debian --VERSION=${VERSION}
  ENV DEBIAN_FRONTEND="noninteractive"
  RUN apt-get -y update
  DO github.com/brad-jones/earthly-devcontainer/utils+FROM_NOW --NAME="ca-certificates"
  RUN apt-get -y install --no-install-recommends ca-certificates
  RUN sed -i 's/http:\/\//https:\/\//g' /etc/apt/sources.list
  DO github.com/brad-jones/earthly-devcontainer/utils+TO_NOW --NAME="ca-certificates"
