VERSION --use-cache-command 0.6

debian:
  ARG VERSION="11"
  FROM debian:${VERSION}-slim

  # VsCode will respect the default shell as configured inside the container
  # see: https://github.com/microsoft/vscode-remote-release/issues/350
  ENV SHELL="/bin/bash"
