VERSION --use-cache-command 0.6

debian:
  FROM debian:11-slim

  # VsCode will respect the default shell as configured inside the container
  # see: https://github.com/microsoft/vscode-remote-release/issues/350
  ENV SHELL="/bin/bash"
