VERSION --use-cache-command 0.6
IMPORT github.com/brad-jones/earthly-devcontainer/debian
IMPORT github.com/brad-jones/earthly-devcontainer/debian/zip

# see: https://linux.die.net/man/1/zip

build:
  FROM debian+builder
  DO debian+FROM_NOW
  RUN apt-get -y install --no-install-recommends zip
  DO debian+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/zip" ]
    COPY zip+build/ /
  END
