VERSION --use-cache-command 0.6
ARG UDCBASE=github.com/brad-jones/earthly-devcontainer/debian

# see: https://gnupg.org

build:
  FROM $UDCBASE+builder
  DO $UDCBASE+FROM_NOW
  RUN apt-get -y install --no-install-recommends gnupg2
  DO $UDCBASE+TO_NOW
  SAVE ARTIFACT /tmp/changed-default/*

INSTALL:
  COMMAND
  IF [ ! -f "/usr/bin/gpg" ]
    COPY $UDCBASE/gpg+build/ /
  END
