on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
          base_sha: ${{ github.event.before }}
          files: |
            .github/workflows/devcontainer.yml
            .devcontainer/Dockerfile
            .devcontainer/bin/.*

      - uses: docker/setup-buildx-action@v1.6.0
        if: steps.changed-files.outputs.any_changed == 'true'

      - uses: docker/login-action@v1.14.1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.9.0
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          tags: ghcr.io/${{ github.repository }}/devcontainer:latest
          context: ./.devcontainer
          push: true