on: { push: { branches: [master] } }

concurrency: release

jobs:
  devcontainer:
    uses: brad-jones/hashdir/.github/workflows/devcontainer.yml@master

  test:
    uses: brad-jones/hashdir/.github/workflows/test.yml@master

  release:
    needs:
      - devcontainer
      - test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/devcontainer:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker-host.sock
    permissions:
      id-token: write
      packages: write
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_KEY }}

      - uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: semantic-release
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}