on:
  workflow_call:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            %LocalAppData%\go-build
            ~/Library/Caches/go-build
            ~/.cache/go-build
            ~/go/pkg/mod
      - run: task build:cmd
      - run: task test